/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#0a0a0a',
        surface: '#141414',
        brand: '#22c55e',
        panel: '#1a1a1a',
        editor: '#111111',
        primary: "#4be277",
        secondary: "#96d59d",
        main: 'rgb(var(--color-main) / <alpha-value>)',
        muted: 'rgb(var(--color-muted) / <alpha-value>)',
        divider: 'rgb(var(--color-divider) / <alpha-value>)',
        foreground: 'rgb(var(--color-foreground) / <alpha-value>)',
        'severity-high': '#ef4444',
        'severity-medium': '#f59e0b',
        'severity-low': '#3b82f6',
        // Landing Page Specifics
        "on-primary-fixed-variant": "#005321",
        "surface-container-high": "#2a2a2a",
        "inverse-on-surface": "#313030",
        "primary-fixed": "#6bff8f",
        "on-error": "#690005",
        "on-surface": "#e5e2e1",
        "secondary-fixed": "#b2f2b7",
        "secondary": "#96d59d",
        "tertiary-container": "#ff8b7c",
        "on-tertiary-container": "#76231b",
        "on-secondary-fixed-variant": "#145126",
        "on-secondary-container": "#89c78f",
        "background": "#131313",
        "inverse-primary": "#006e2f",
        "surface-container-lowest": "#0e0e0e",
        "surface-dim": "#131313",
        "surface-bright": "#3a3939",
        "surface-container-highest": "#353534",
        "secondary-fixed-dim": "#96d59d",
        "on-tertiary": "#60130d",
        "outline": "#869585",
        "primary-container": "#22c55e",
        "on-primary-fixed": "#002109",
        "secondary-container": "#175428",
        "on-tertiary-fixed-variant": "#7f2a21",
        "on-background": "#e5e2e1",
        "surface-variant": "#353534",
        "on-secondary": "#003915",
        "on-primary": "#003915",
        "on-tertiary-fixed": "#410001",
        "error": "#ffb4ab",
        "inverse-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "surface-container": "#201f1f",
        "tertiary-fixed-dim": "#ffb4a9",
        "outline-variant": "#3d4a3d",
        "primary-fixed-dim": "#4ae176",
        "tertiary": "#ffb5ab",
        "tertiary-fixed": "#ffdad5",
        "on-primary-container": "#004b1e",
        "surface-container-low": "#1c1b1b",
        "surface-tint": "#4ae176",
        "surface": "#131313",
        "on-surface-variant": "#bccbb9",
        "error-container": "#93000a",
        "on-secondary-fixed": "#002109"
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["DM Sans"],
        label: ["Inter"],
        mono: ["DM Mono"]
      },
      borderRadius: { "DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px" },
    },
  },
  plugins: [],
}
